### PR TITLE
Dem

### PR DESCRIPTION
**Pull request by ululi1970**
Ciao Ed,
a few notes: MassBay should be pulled. The ThreeDBeamGeneration stuff is for 
the generation of IW from an isolated bump. Not sure if you want to keep it 
as part of Master. It is an example of how to force a flow by assigning a Diri condition
on the normal velocities. If you ax it, do not forget to remove the relevant stuff from ProblemContext.
See you Tuesday.

### CODE REVIEW

**Comment by EdSantilli** [comment]
I see you use a counter to free memory in DEMMap. Did you observe a memory leak without this code? The RefCountedPtr should automatically turn the lights out for you.

**Comment by ululi1970** [comment]
Ah, so that what RefCounted means. And that is why if instead of the .delete() call 
I do a for(int level=maxLevel-1;level>-1;--level) {delete s_XXX[level]} I get a seg fault at the end. It has 
already been deleted. Well, live and learn. And no, I did not observe a memory leak, but 
also I did not check for one. For running SOMAR standalone, or with a LES, it does not
matter, but if SOMAR ever becomes part of a larger code that calls SOMAR on an as-needed base,
I just wanted to make sure that no memory is left hang  out to dry.

**Comment by EdSantilli** [comment]
Okay. I checked and observed no memory leak. Nevertheless, I am going to leave the code intact. There's no reason we can't clear the vector manually.

**Comment by ululi1970** [comment]
Good. Happy Father's day BTW!

**Comment by EdSantilli** [comment]
I am leaving ThreeDBumpBCUtil out of this merge. The DEMMap stuff is a large merge as is and I'd like to keep it separate from other enhancements. Also, I think ThreeDBumpBCUtil should not be its own class, but instead should be the default behavior of BeamGenerationBCUtil when DIM=3. I would also like to incorporate your elliptic tidal forcing as default behavior in 3D. We can talk more about this in another thread.

**Pull request merged**
